"""转移轨道设计。

按数学类型组织（ADR 0011 迁移，源：``transfer/``）：脉冲路径（lambert/
three_body_lambert/multi_impulse）、自然动力学路径（low_energy/manifold，
覆盖引力辅助数学内核）、低推力路径（low_thrust/）、任务层（search/
optimize/porkchop）。

编排器在 ``orchestrator.py``（接收 transfer_type：HMN/LGA/WSB/
low_thrust/PCN，按枚举选路径组合底层数学模块）；结果契约 dataclass 与
top-N / state_frame 常量在 ``contracts.py``。包入口是纯 re-export 惰性
门面：子模块按首次访问加载，导入本包不再触发全部 33 个子模块的急切
加载。

已实现：HMN 霍曼转移、LGA 月球引力辅助、WSB 太阳引力辅助、小推力转移、
PCN patched-conic 目标参数化（月心 B 平面 / 双曲渐近线）。
"""

from __future__ import annotations

__all__ = [
    "TransferSearch",
    "Transfer",
    "TransferConfig",
    "TransferOptimizationResult",
    "DROTRONLPOptimizer",
    "NLPOptimizationVariables",
    "DEFAULT_MIN_DISTANCE_THRESHOLD_DU",
    "load_orbit_from_json",
    "optimize_transfer",
    "optimize_with_copt",
    "ImpulsivePropulsion",
    "TerminalCondition",
    "OrbitTerminal",
    "StateTerminal",
    "LambertSolution",
    "solve_lambert",
    "solve_lambert_batch",
    "FlybyEvaluation",
    "MgaCandidate",
    "MgaSearchResult",
    "evaluate_flyby",
    "flyby_pericenter_radius",
    "flyby_turn_angle",
    "heliocentric_tisserand",
    "search_mga_chains",
    "MgaRefinementResult",
    "refine_mga_chain",
    "ChainLegEval",
    "ChainLegRequest",
    "FlybyConstraintEval",
    "LegKernel",
    "MinimaxSolveResult",
    "SquareSolveResult",
    "VariableLayout",
    "evaluate_chain",
    "flyby_node_constraints",
    "solve_minimax",
    "solve_square",
    "PorkchopData",
    "porkchop",
    "ParetoFront",
    "pareto_front",
    "NSGA2Result",
    "nsga2",
    "MissionAssessment",
    "SolutionDatabase",
    "ThreeBodyLambert",
    "TransferArc",
    "TransferSolution",
    "CoastArc",
    "Impulse",
    "MultiImpulseTransfer",
    "PrimerVectorReport",
    "PatchCandidate",
    "patch_manifolds",
    "design_low_energy_transfer",
    "EngineConfig",
    "LowThrustSegment",
    "LowThrustShooting",
    "LowThrustShootingSolution",
    "LowThrustCollocation",
    "ThrustArc",
    "ThrustArcSequence",
    "DEFAULT_THRUST_LEVELS",
    "sequence_from_controls",
    "controls_from_sequence",
    "qlaw_guess",
    "rv_to_keplerian",
    "SpiralGuess",
    "constant_thrust_final_mass",
    "constant_thrust_transfer_time",
    "edelbaum_delta_v",
    "edelbaum_delta_v_inclined",
    "mass_flow_rate",
    "nep_available_power",
    "sep_available_power",
    "spiral_arc_guess",
    "thrust_from_power",
    "SimsFlanaganFlybyResult",
    "SimsFlanaganLegSolution",
    "SimsFlanaganMultiLegProblem",
    "SimsFlanaganMultiLegSolution",
    "SimsFlanaganNode",
    "SimsFlanaganProblem",
    "SimsFlanaganPropulsion",
    "SimsFlanaganSolution",
    "TliParams",
    "construct_departure_state",
    "hohmann_delta_v",
    "hohmann_tof",
    "scan_lambert_delta_v",
    "ephemeris_shoot_transfer",
    "HmnTransferDetails",
    "LgaTransferDetails",
    "LgaSearchParams",
    "LgaCandidate",
    "CandidateSearchResult",
    "WsbTransferDetails",
    "WsbSearchParams",
    "WsbCandidate",
    "LowThrustTransferDetails",
    "ManeuverEvent",
    "TransferCandidate",
    "DEFAULT_TOP_N",
    "STATE_FRAME_SYNODIC_BARYCENTRIC_KM",
    "STATE_FRAME_FORCE_MODEL_STATE",
    "STATE_FRAME_GCRS_KM",
    "AsymptoteParams",
    "BPlaneParams",
    "PcnBplaneTarget",
    "PcnSearchParams",
    "PcnSolution",
    "PcnTransferDetails",
    "asymptote_from_vinf_vector",
    "bplane_from_state",
    "bplane_jacobian_from_state",
    "hyperbolic_time_to_periapsis",
    "perilune_radius_closed_form",
    "perilune_state_from_bplane",
    "state_from_bplane",
    "vinf_vector_from_asymptote",
    "solve_pcn",
    "transfer_orbit",
]

#: 惰性导出：名字 → 定义所在子模块（相对本包）。经 PEP 562 在首次访问时
#: 加载，包导入保持轻量（issue #749 前的急切导入 importtime 累计 326 ms）。
#: 覆盖 ``__all__`` 全部名字、``G0_MPS2``（不在 ``__all__`` 但被测试导入）
#: 与编排器/契约的私有助手。
_LAZY_EXPORTS = {
    # contracts：结果契约与常量
    "ManeuverEvent": "contracts",
    "TransferCandidate": "contracts",
    "TransferDesignResult": "contracts",
    "HmnTransferDetails": "contracts",
    "LgaTransferDetails": "contracts",
    "WsbTransferDetails": "contracts",
    "LowThrustTransferDetails": "contracts",
    "PcnTransferDetails": "contracts",
    "DEFAULT_TOP_N": "contracts",
    "STATE_FRAME_SYNODIC_BARYCENTRIC_KM": "contracts",
    "STATE_FRAME_FORCE_MODEL_STATE": "contracts",
    "STATE_FRAME_GCRS_KM": "contracts",
    # orchestrator：编排器入口与编排私有助手
    "transfer_orbit": "orchestrator",
    "_extract_target_state": "orchestrator",
    "_propagate_synodic_leg": "orchestrator",
    "_join_transfer_legs": "orchestrator",
    "_synodic_to_gcrs": "orchestrator",
    "_gcrs_to_synodic": "orchestrator",
    "_moon_state_gcrs": "orchestrator",
    "_propagate_two_body_checked": "orchestrator",
    "_equivalent_delta_v": "orchestrator",
    "_transfer_orbit_pcn": "orchestrator",
    "_pcn_details": "orchestrator",
    "_pcn_stages": "orchestrator",
    "_transfer_orbit_lga": "orchestrator",
    "_transfer_orbit_wsb": "orchestrator",
    "_transfer_orbit_low_thrust": "orchestrator",
    "_transfer_orbit_hmn": "orchestrator",
    # 数学内核与任务层子模块
    "AsymptoteParams": "bplane",
    "BPlaneParams": "bplane",
    "asymptote_from_vinf_vector": "bplane",
    "bplane_from_state": "bplane",
    "bplane_jacobian_from_state": "bplane",
    "hyperbolic_time_to_periapsis": "bplane",
    "perilune_radius_closed_form": "bplane",
    "perilune_state_from_bplane": "bplane",
    "state_from_bplane": "bplane",
    "vinf_vector_from_asymptote": "bplane",
    "TransferArc": "config",
    "TransferConfig": "config",
    "TransferOptimizationResult": "config",
    "TransferSolution": "config",
    "MU_EARTH": "hohmann",
    "R_EARTH": "hohmann",
    "TliParams": "hohmann",
    "construct_departure_state": "hohmann",
    "eci_to_synodic_display": "hohmann",
    "ephemeris_shoot_transfer": "hohmann",
    "hohmann_delta_v": "hohmann",
    "hohmann_tof": "hohmann",
    "hohmann_transfer_states": "hohmann",
    "scan_lambert_delta_v": "hohmann",
    "LambertSolution": "lambert",
    "solve_lambert": "lambert",
    "solve_lambert_batch": "lambert",
    "LgaCandidate": "lga",
    "LgaSearchParams": "lga",
    "search_lga_trajectories": "lga",
    "PatchCandidate": "low_energy",
    "design_low_energy_transfer": "low_energy",
    "patch_manifolds": "low_energy",
    "LowThrustCollocation": "lowthrust_collocation",
    "EngineConfig": "lowthrust_shooting",
    "LowThrustSegment": "lowthrust_shooting",
    "LowThrustShooting": "lowthrust_shooting",
    "LowThrustShootingSolution": "lowthrust_shooting",
    "FlybyEvaluation": "mga",
    "MgaCandidate": "mga",
    "MgaSearchResult": "mga",
    "evaluate_flyby": "mga",
    "flyby_pericenter_radius": "mga",
    "flyby_turn_angle": "mga",
    "heliocentric_tisserand": "mga",
    "search_mga_chains": "mga",
    "MgaRefinementResult": "mga_refine",
    "refine_mga_chain": "mga_refine",
    "MissionAssessment": "mission_assessment",
    "CoastArc": "multi_impulse",
    "Impulse": "multi_impulse",
    "MultiImpulseTransfer": "multi_impulse",
    "PrimerVectorReport": "multi_impulse",
    "propagate_two_body": "multi_impulse",
    "ChainLegEval": "multisegment",
    "ChainLegRequest": "multisegment",
    "FlybyConstraintEval": "multisegment",
    "LegKernel": "multisegment",
    "MinimaxSolveResult": "multisegment",
    "SquareSolveResult": "multisegment",
    "VariableLayout": "multisegment",
    "evaluate_chain": "multisegment",
    "flyby_node_constraints": "multisegment",
    "solve_minimax": "multisegment",
    "solve_square": "multisegment",
    "NSGA2Result": "nsga2",
    "nsga2": "nsga2",
    "PcnBplaneTarget": "pcn",
    "PcnSearchParams": "pcn",
    "PcnSolution": "pcn",
    "solve_pcn": "pcn",
    "ParetoFront": "porkchop",
    "PorkchopData": "porkchop",
    "pareto_front": "porkchop",
    "porkchop": "porkchop",
    "ImpulsivePropulsion": "propulsion",
    "qlaw_guess": "qlaw",
    "rv_to_keplerian": "qlaw",
    "SpiralGuess": "sep",
    "constant_thrust_final_mass": "sep",
    "constant_thrust_transfer_time": "sep",
    "edelbaum_delta_v": "sep",
    "edelbaum_delta_v_inclined": "sep",
    "mass_flow_rate": "sep",
    "nep_available_power": "sep",
    "sep_available_power": "sep",
    "spiral_arc_guess": "sep",
    "thrust_from_power": "sep",
    "SimsFlanaganFlybyResult": "sims_flanagan",
    "SimsFlanaganLegSolution": "sims_flanagan",
    "SimsFlanaganMultiLegProblem": "sims_flanagan",
    "SimsFlanaganMultiLegSolution": "sims_flanagan",
    "SimsFlanaganNode": "sims_flanagan",
    "SimsFlanaganProblem": "sims_flanagan",
    "SimsFlanaganPropulsion": "sims_flanagan",
    "SimsFlanaganSolution": "sims_flanagan",
    "SolutionDatabase": "solution_database",
    "OrbitTerminal": "terminal",
    "StateTerminal": "terminal",
    "TerminalCondition": "terminal",
    "ThreeBodyLambert": "three_body_lambert",
    "DEFAULT_THRUST_LEVELS": "thrust_arcs",
    "G0_MPS2": "thrust_arcs",
    "ThrustArc": "thrust_arcs",
    "ThrustArcSequence": "thrust_arcs",
    "controls_from_sequence": "thrust_arcs",
    "sequence_from_controls": "thrust_arcs",
    "Transfer": "transfer",
    "DROTRONLPOptimizer": "transfer_optimization",
    "NLPOptimizationVariables": "transfer_optimization",
    "optimize_transfer": "transfer_optimization",
    "optimize_with_copt": "transfer_optimization",
    "DEFAULT_MIN_DISTANCE_THRESHOLD_DU": "transfer_search",
    "TransferSearch": "transfer_search",
    "load_orbit_from_json": "transfer_search",
    "WsbCandidate": "wsb",
    "WsbSearchParams": "wsb",
    "search_wsb_trajectories": "wsb",
}

#: 惰性导出到包外定义模块的名字（``__all__`` 里的 ``CandidateSearchResult``
#: 原从 ``algorithm.results`` re-export，映射到绝对模块名）。
_EXTERNAL_LAZY_EXPORTS = {
    "CandidateSearchResult": "e2m2e.algorithm.results",
}


def __getattr__(name: str):  # PEP 562
    from importlib import import_module

    if name in _LAZY_EXPORTS:
        module = import_module(f"{__name__}.{_LAZY_EXPORTS[name]}")
    elif name in _EXTERNAL_LAZY_EXPORTS:
        module = import_module(_EXTERNAL_LAZY_EXPORTS[name])
    else:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(module, name)
    globals()[name] = value
    return value
